cache: 
  - packages -> **\packages.config

version: 1.0.{build}

branches:
  only:
  - master

nuget:
  account_feed: true



before_build:
- cmd: nuget restore
configuration: Release

image: Visual Studio 2017

build:
  project: WebApplication1.sln
  publish_wap_octopus: true
  verbosity: minimal

deploy:
  provider: GitHub
  description: "Foo"
  auth_token:
    secure: w3IVtGpacFdouiFDUcp4snp8yBelm30TUWHf+69NJ0Oh3LchiLQdMigkWWVppayw
  draft: false
  prerelease: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true